/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./estrutura-organizacional/**/*.html", "./assets/js/**/*.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#862120",
        "on-primary": "#ffffff",
        "primary-container": "#600209",
        "on-primary-container": "#ec6c65",
        "primary-fixed": "#ffdad7",
        "primary-fixed-dim": "#ffb3ad",
        "on-primary-fixed": "#410004",
        "on-primary-fixed-variant": "#862120",
        "inverse-primary": "#ffb3ad",
        secondary: "#944a00",
        "on-secondary": "#ffffff",
        "secondary-container": "#ff9f56",
        "on-secondary-container": "#723700",
        "secondary-fixed": "#ffdcc6",
        "secondary-fixed-dim": "#ffb784",
        "on-secondary-fixed": "#301400",
        "on-secondary-fixed-variant": "#713700",
        tertiary: "#001b26",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#013141",
        "on-tertiary-container": "#7399ad",
        "tertiary-fixed": "#c1e8fd",
        "tertiary-fixed-dim": "#a5cce0",
        "on-tertiary-fixed": "#001f2a",
        "on-tertiary-fixed-variant": "#244b5c",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#fff8f7",
        "on-background": "#1d1b1b",
        surface: "#fff8f7",
        "on-surface": "#1d1b1b",
        "surface-variant": "#e8e1e0",
        "on-surface-variant": "#574240",
        "surface-bright": "#fff8f7",
        "surface-dim": "#dfd9d8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f9f2f1",
        "surface-container": "#f3eceb",
        "surface-container-high": "#ede7e6",
        "surface-container-highest": "#e8e1e0",
        "surface-tint": "#a63835",
        "inverse-surface": "#33302f",
        "inverse-on-surface": "#f6efee",
        outline: "#8b716f",
        "outline-variant": "#dec0bd",
      },
      fontFamily: {
        headline: ["Inter", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
